# Generated by Django 3.2.5 on 2022-12-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveBigIntegerField(default=0)),
                ('dislike', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
